## Python Objects and Map Function

Objects are instances of a class, and class is a blueprint for objects. They determine the attributes and functionalities of an object.

## Step 1: Working with Classes


Let's create a class using the class keyword:
- Create a class called House
- Define a class variable **Rented House** that says the house type is equal to a Rented House
- Define the constructor (__init__) with instance variables **floors**, **rooms** and **price**

In [ ]:
class House:
    house_type = 'Rented House'
    def __init__(self,floors,rooms,price):
        self.floors = floors 
        self.rooms = rooms 
        self.price = price

- Create an object (instance) **home** of the house class with 1 floor, 3 rooms and a price of 25000
- Access and modify its attributes
- Add new attributes dynamically

In [ ]:
home = House(1,3,25000)

Let's check the type of the home object.

In [ ]:
type(home)

__main__.House

**Observation**

The object type is House class

Now let's access the variable **floors**, **rooms**, **price** and **house_type**. We can access the variables of the home object using the dot(.) operator.

In [ ]:
home.floors

1

In [ ]:
home.rooms

3

In [ ]:
home.price

25000

In [ ]:
home.house_type

'Rented House'

Now, let's modify the house price.

- Access the **price** variable with the dot operator
- Assign the new value to home.price

In [ ]:
home.price = 28000

Let's print the value.

In [ ]:
print(home.price)

28000

We can also delete the objects of a class using the **del** keyword. del would delete the entire object. 

If we want to delete only a specific attribute, we can do this with del as well, such as typing del home.floors to remove this attribute.

In [ ]:
del home.floors

Try to access the floors attribute again:

In [ ]:
home.floors

AttributeError: ignored

**Observation**

Trying to access the deleted attribute from an object throws an error.

We can also add multiple attributes dynamically. 

Now, let's add the attribute **floors** again.

In [ ]:
home.floors = 2

**Observation:**

Here, we have added the floors attribute again dynamically.

Now, let's add a new attribute **bathroom** to home dynamically.

In [ ]:
home.bathrooms = 4

In [ ]:
print(home.bathrooms)

4

## Step 2: Using the Map Function


Maps in Python are very useful when you are trying to apply a function to an iterable. map() applies a function to each item in an iterable and returns a new iterable or a map object. This can then be converted to a list, a tuple or whichever is suited for our programming.


- Create a list of integers
- Create a function **squares** to compute the squares of a given number

In [ ]:
l = [1,2,3,4,5]
def squares(x):
    return x*x

Now let's update the list with the squares of the list items using the traditional **for** **loop** method. Here we create a function called **squares** that takes the parameter x square of x. Now, let's apply this to each element with a **for** **loop**. 

- Define an empty list to add sqaures 
- Iterate through the list 'l' using for loop
- Append squares to the updated list

In [ ]:
updated_list = []
for i in l:
    updated_list.append(squares(i))

Now, let's display the updated list.

In [ ]:
updated_list

[1, 4, 9, 16, 25]

**Observation**

The updated list has squares of each list item.

Now, let's do the same using map function.
- Declare a variable **updated_list**, and call the **map** function with the function name **squares** and list **l** as attributes
- Convert the map object to list, and assign to the **updated_list** variable

In [ ]:
updated_list = list(map(squares,l))

Let's display the updated list.

In [ ]:
updated_list

[1, 4, 9, 16, 25]

**Observation**

**updated_list** contains the squares of list elements.

Now, let's check the type of the map object.

In [ ]:
type(map(squares,l))

map

**Observation**

The type of the map object is map.

Now, let's apply the map function to strings and multiple iterables.
- Define a string **s**
- Define a function to return the uppercase of a character
- Apply the map function to the string defined, and assign it back to the same string
- Iterate through each character of the string and apply a space using the delimiter **end = ' '**

In [ ]:
s = "Hello World"
def return_upper(x):
    return x.upper()
s = map(return_upper,s)
for i in s:
    print(i,end = ' ')

H E L L O   W O R L D

In the above example, we have defined a function to convert all the characters to uppercase. We can avoid this by using the lambda function. Now, let's use the lambda function to convert the characters into uppercase.
- Define a string **s**
- Call the map function with attributes lambda and function uppercase applied to it and string **s**

In [ ]:
s = " Hello World "
s = map(lambda x: x.upper(),s)

Now, let's display the updated string.

In [ ]:
for i in s:
    print(i,end = ' ')

**Observation**

All characters in the string are now in uppercase.

Now, let's see how to convert multiple strings into uppercase.
- Create a variable for updated strings
- Call map function with lambda with expression x maps to x's uppercase and the strings

In [ ]:
s1 = 'Hello World'
s2 = 'Welcome to Simplilearn'
updated_strings = map(lambda x:x.upper(),[s1,s2])

Now, let's display the updated string.

In [ ]:
for i in updated_strings:
    print(i)

HELLO WORLD
WELCOME TO SIMPLILEARN

**Observation**

The characters of both the strings are in uppercase now.